name: timebased_otp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2
  
dependencies:
  flutter:
    sdk: flutter
  totp: ^0.1.0
  hotp: ^0.1.0
  cupertino_icons: ^1.0.8
  test: ^1.25.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
